# Generated by Django 5.0.1 on 2024-02-23 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_pinned',
            new_name='pinned',
        ),
    ]
